; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve < %s | FileCheck %s --check-prefix=CHECK-SD
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve -global-isel -aarch64-disable-sve-gisel=false < %s | FileCheck %s --check-prefix=CHECK-GI

define <vscale x 4 x float> @test(<vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; CHECK-SD-LABEL: test:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    fmul z1.s, z0.s, z1.s
; CHECK-SD-NEXT:    fadd z0.s, z0.s, z1.s
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: test:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    fmul z1.s, z0.s, z1.s
; CHECK-GI-NEXT:    fadd z0.s, z0.s, z1.s
; CHECK-GI-NEXT:    ret
entry:
  %c = fmul <vscale x 4 x float> %a, %b
  %d = fadd <vscale x 4 x float> %a, %c
  ret <vscale x 4 x float> %d
}


