# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=riscv32 -mattr=+d,+m,+v -run-pass=regbankselect \
# RUN:   -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=RV32I %s

---
name:            insertelement_nxv1i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; RV32I-LABEL: name: insertelement_nxv1i8
    ; RV32I: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s8>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 1 x s8>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 1 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s8>) = G_IMPLICIT_DEF
    %5:_(s32) = G_CONSTANT i32 0
    %1:_(s8) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(<vscale x 1 x s8>) = G_INSERT_VECTOR_ELT %0, %1(s8), %2(s8)
    $v8 = COPY %3(<vscale x 1 x s8>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv2i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8

    ; RV32I-LABEL: name: insertelement_nxv2i8
    ; RV32I: liveins: $v8
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s8>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 2 x s8>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 2 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s8>) = G_IMPLICIT_DEF
    %5:_(s32) = G_CONSTANT i32 1
    %1:_(s8) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(<vscale x 2 x s8>) = G_INSERT_VECTOR_ELT %0, %1(s8), %2(s8)
    $v8 = COPY %3(<vscale x 2 x s8>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv4i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8

    ; RV32I-LABEL: name: insertelement_nxv4i8
    ; RV32I: liveins: $v8
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 4 x s8>) = COPY $v8
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 4 x s8>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 4 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s8>) = COPY $v8
    %5:_(s32) = G_CONSTANT i32 0
    %1:_(s8) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(<vscale x 4 x s8>) = G_INSERT_VECTOR_ELT %0, %1(s8), %2(s8)
    $v8 = COPY %3(<vscale x 4 x s8>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv8i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8

    ; RV32I-LABEL: name: insertelement_nxv8i8
    ; RV32I: liveins: $v8
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 8 x s8>) = COPY $v8
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 8 x s8>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 8 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 8 x s8>) = COPY $v8
    %5:_(s32) = G_CONSTANT i32 1
    %1:_(s8) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(<vscale x 8 x s8>) = G_INSERT_VECTOR_ELT %0, %1(s8), %2(s8)
    $v8 = COPY %3(<vscale x 8 x s8>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv16i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m2, $x10, $x11

    ; RV32I-LABEL: name: insertelement_nxv16i8
    ; RV32I: liveins: $v8m2, $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 16 x s8>) = COPY $v8m2
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[COPY1]](s32)
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[COPY2]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 16 x s8>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8m2 = COPY [[IVEC]](<vscale x 16 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    %0:_(<vscale x 16 x s8>) = COPY $v8m2
    %1:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %3:_(s8) = G_TRUNC %1(s32)
    %4:_(s8) = G_TRUNC %2(s32)
    %5:_(<vscale x 16 x s8>) = G_INSERT_VECTOR_ELT %0, %3(s8), %4(s8)
    $v8m2 = COPY %5(<vscale x 16 x s8>)
    PseudoRET implicit $v8m2

...
---
name:            insertelement_nxv32i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m4, $x10, $x11

    ; RV32I-LABEL: name: insertelement_nxv32i8
    ; RV32I: liveins: $v8m4, $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 32 x s8>) = COPY $v8m4
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[COPY1]](s32)
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[COPY2]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 32 x s8>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8m4 = COPY [[IVEC]](<vscale x 32 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    %0:_(<vscale x 32 x s8>) = COPY $v8m4
    %1:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %3:_(s8) = G_TRUNC %1(s32)
    %4:_(s8) = G_TRUNC %2(s32)
    %5:_(<vscale x 32 x s8>) = G_INSERT_VECTOR_ELT %0, %3(s8), %4(s8)
    $v8m4 = COPY %5(<vscale x 32 x s8>)
    PseudoRET implicit $v8m4

...
---
name:            insertelement_nxv64i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; RV32I-LABEL: name: insertelement_nxv64i8
    ; RV32I: [[DEF:%[0-9]+]]:vrb(<vscale x 64 x s8>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s8) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s8) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 64 x s8>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s8), [[TRUNC1]](s8)
    ; RV32I-NEXT: $v8m8 = COPY [[IVEC]](<vscale x 64 x s8>)
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    %0:_(<vscale x 64 x s8>) = G_IMPLICIT_DEF
    %5:_(s32) = G_CONSTANT i32 0
    %1:_(s8) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 0
    %2:_(s8) = G_TRUNC %4(s32)
    %3:_(<vscale x 64 x s8>) = G_INSERT_VECTOR_ELT %0, %1(s8), %2(s8)
    $v8m8 = COPY %3(<vscale x 64 x s8>)
    PseudoRET implicit $v8m8

...
---
name:            insertelement_nxv1i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; RV32I-LABEL: name: insertelement_nxv1i16
    ; RV32I: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s16>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s16) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s16) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 1 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[TRUNC1]](s16)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 1 x s16>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s16>) = G_IMPLICIT_DEF
    %5:_(s32) = G_CONSTANT i32 0
    %1:_(s16) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 0
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(<vscale x 1 x s16>) = G_INSERT_VECTOR_ELT %0, %1(s16), %2(s16)
    $v8 = COPY %3(<vscale x 1 x s16>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv2i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; RV32I-LABEL: name: insertelement_nxv2i16
    ; RV32I: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s16>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s16) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s16) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 2 x s16>) = G_INSERT_VECTOR_ELT [[DEF]], [[TRUNC]](s16), [[TRUNC1]](s16)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 2 x s16>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s16>) = G_IMPLICIT_DEF
    %5:_(s32) = G_CONSTANT i32 1
    %1:_(s16) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(<vscale x 2 x s16>) = G_INSERT_VECTOR_ELT %0, %1(s16), %2(s16)
    $v8 = COPY %3(<vscale x 2 x s16>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv4i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8

    ; RV32I-LABEL: name: insertelement_nxv4i16
    ; RV32I: liveins: $v8
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 4 x s16>) = COPY $v8
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s16) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s16) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 4 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s16), [[TRUNC1]](s16)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 4 x s16>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s16>) = COPY $v8
    %5:_(s32) = G_CONSTANT i32 0
    %1:_(s16) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 0
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(<vscale x 4 x s16>) = G_INSERT_VECTOR_ELT %0, %1(s16), %2(s16)
    $v8 = COPY %3(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv8i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m2

    ; RV32I-LABEL: name: insertelement_nxv8i16
    ; RV32I: liveins: $v8m2
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 8 x s16>) = COPY $v8m2
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s16) = G_TRUNC [[C]](s32)
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s16) = G_TRUNC [[C1]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 8 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s16), [[TRUNC1]](s16)
    ; RV32I-NEXT: $v8m2 = COPY [[IVEC]](<vscale x 8 x s16>)
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    %0:_(<vscale x 8 x s16>) = COPY $v8m2
    %5:_(s32) = G_CONSTANT i32 1
    %1:_(s16) = G_TRUNC %5(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %2:_(s16) = G_TRUNC %4(s32)
    %3:_(<vscale x 8 x s16>) = G_INSERT_VECTOR_ELT %0, %1(s16), %2(s16)
    $v8m2 = COPY %3(<vscale x 8 x s16>)
    PseudoRET implicit $v8m2

...
---
name:            insertelement_nxv16i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m4, $x10, $x11

    ; RV32I-LABEL: name: insertelement_nxv16i16
    ; RV32I: liveins: $v8m4, $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 16 x s16>) = COPY $v8m4
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s16) = G_TRUNC [[COPY1]](s32)
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s16) = G_TRUNC [[COPY2]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 16 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s16), [[TRUNC1]](s16)
    ; RV32I-NEXT: $v8m4 = COPY [[IVEC]](<vscale x 16 x s16>)
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    %0:_(<vscale x 16 x s16>) = COPY $v8m4
    %1:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %3:_(s16) = G_TRUNC %1(s32)
    %4:_(s16) = G_TRUNC %2(s32)
    %5:_(<vscale x 16 x s16>) = G_INSERT_VECTOR_ELT %0, %3(s16), %4(s16)
    $v8m4 = COPY %5(<vscale x 16 x s16>)
    PseudoRET implicit $v8m4

...
---
name:            insertelement_nxv32i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m8, $x10, $x11

    ; RV32I-LABEL: name: insertelement_nxv32i16
    ; RV32I: liveins: $v8m8, $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 32 x s16>) = COPY $v8m8
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I-NEXT: [[TRUNC:%[0-9]+]]:gprb(s16) = G_TRUNC [[COPY1]](s32)
    ; RV32I-NEXT: [[TRUNC1:%[0-9]+]]:gprb(s16) = G_TRUNC [[COPY2]](s32)
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 32 x s16>) = G_INSERT_VECTOR_ELT [[COPY]], [[TRUNC]](s16), [[TRUNC1]](s16)
    ; RV32I-NEXT: $v8m8 = COPY [[IVEC]](<vscale x 32 x s16>)
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    %0:_(<vscale x 32 x s16>) = COPY $v8m8
    %1:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %3:_(s16) = G_TRUNC %1(s32)
    %4:_(s16) = G_TRUNC %2(s32)
    %5:_(<vscale x 32 x s16>) = G_INSERT_VECTOR_ELT %0, %3(s16), %4(s16)
    $v8m8 = COPY %5(<vscale x 32 x s16>)
    PseudoRET implicit $v8m8

...
---
name:            insertelement_nxv1i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; RV32I-LABEL: name: insertelement_nxv1i32
    ; RV32I: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s32>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 1 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[C]](s32), [[C1]](s32)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 1 x s32>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s32>) = G_IMPLICIT_DEF
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<vscale x 1 x s32>) = G_INSERT_VECTOR_ELT %0, %1(s32), %2(s32)
    $v8 = COPY %3(<vscale x 1 x s32>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv2i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; RV32I-LABEL: name: insertelement_nxv2i32
    ; RV32I: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s32>) = G_IMPLICIT_DEF
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 2 x s32>) = G_INSERT_VECTOR_ELT [[DEF]], [[C]](s32), [[C1]](s32)
    ; RV32I-NEXT: $v8 = COPY [[IVEC]](<vscale x 2 x s32>)
    ; RV32I-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s32>) = G_IMPLICIT_DEF
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<vscale x 2 x s32>) = G_INSERT_VECTOR_ELT %0, %1(s32), %2(s32)
    $v8 = COPY %3(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            insertelement_nxv4i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m2

    ; RV32I-LABEL: name: insertelement_nxv4i32
    ; RV32I: liveins: $v8m2
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 4 x s32>) = COPY $v8m2
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 4 x s32>) = G_INSERT_VECTOR_ELT [[COPY]], [[C]](s32), [[C1]](s32)
    ; RV32I-NEXT: $v8m2 = COPY [[IVEC]](<vscale x 4 x s32>)
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    %0:_(<vscale x 4 x s32>) = COPY $v8m2
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_CONSTANT i32 0
    %3:_(<vscale x 4 x s32>) = G_INSERT_VECTOR_ELT %0, %1(s32), %2(s32)
    $v8m2 = COPY %3(<vscale x 4 x s32>)
    PseudoRET implicit $v8m2

...
---
name:            insertelement_nxv8i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m4

    ; RV32I-LABEL: name: insertelement_nxv8i32
    ; RV32I: liveins: $v8m4
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 8 x s32>) = COPY $v8m4
    ; RV32I-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 8 x s32>) = G_INSERT_VECTOR_ELT [[COPY]], [[C]](s32), [[C1]](s32)
    ; RV32I-NEXT: $v8m4 = COPY [[IVEC]](<vscale x 8 x s32>)
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    %0:_(<vscale x 8 x s32>) = COPY $v8m4
    %1:_(s32) = G_CONSTANT i32 1
    %2:_(s32) = G_CONSTANT i32 1
    %3:_(<vscale x 8 x s32>) = G_INSERT_VECTOR_ELT %0, %1(s32), %2(s32)
    $v8m4 = COPY %3(<vscale x 8 x s32>)
    PseudoRET implicit $v8m4

...
---
name:            insertelement_nxv16i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $v8m8, $x10, $x11

    ; RV32I-LABEL: name: insertelement_nxv16i32
    ; RV32I: liveins: $v8m8, $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:vrb(<vscale x 16 x s32>) = COPY $v8m8
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x11
    ; RV32I-NEXT: [[IVEC:%[0-9]+]]:vrb(<vscale x 16 x s32>) = G_INSERT_VECTOR_ELT [[COPY]], [[COPY1]](s32), [[COPY2]](s32)
    ; RV32I-NEXT: $v8m8 = COPY [[IVEC]](<vscale x 16 x s32>)
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    %0:_(<vscale x 16 x s32>) = COPY $v8m8
    %1:_(s32) = COPY $x10
    %2:_(s32) = COPY $x11
    %3:_(<vscale x 16 x s32>) = G_INSERT_VECTOR_ELT %0, %1(s32), %2(s32)
    $v8m8 = COPY %3(<vscale x 16 x s32>)
    PseudoRET implicit $v8m8

...
