# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32  -run-pass=regbankselect \
# RUN:   -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefixes=BOTH,RV32 %s
# RUN: llc -mtriple=riscv64  -run-pass=regbankselect \
# RUN:   -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefixes=BOTH,RV64 %s

---
name:            test_args_nxv1i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1i8
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s8>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s8>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2i8
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s8>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s8>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv4i8
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 4 x s8>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s8>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv8i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv8i8
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 8 x s8>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s8>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv16i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv16i8
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 16 x s8>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s8>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv32i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv32i8
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 32 x s8>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 32 x s8>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv64i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv64i8
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 64 x s8>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 64 x s8>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv1i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1i16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2i16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv4i16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 4 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv8i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv8i16
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 8 x s16>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s16>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv16i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv16i16
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 16 x s16>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s16>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv32i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv32i16
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 32 x s16>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 32 x s16>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv1i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1i32
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s32>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s32>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2i32
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s32>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s32>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv4i32
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 4 x s32>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s32>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv8i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv8i32
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 8 x s32>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s32>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv16i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv16i32
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 16 x s32>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s32>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv1i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1i64
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s64>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s64>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv2i64
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 2 x s64>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s64>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv4i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv4i64
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 4 x s64>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s64>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv8i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv8i64
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 8 x s64>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s64>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv64i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv64i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 64 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 64 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv32i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv32i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 32 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 32 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv16i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv16i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 16 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv8i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv8i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 8 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv4i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 4 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv1i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1i1
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s1>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s1>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv1f32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1f32
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s32>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s32>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2f32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2f32
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s32>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s32>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4f32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv4f32
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 4 x s32>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s32>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv8f32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv8f32
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 8 x s32>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s32>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv16f32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv16f32
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 16 x s32>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s32>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv1f64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1f64
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s64>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s64>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2f64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv2f64
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 2 x s64>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s64>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv4f64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv4f64
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 4 x s64>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s64>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv8f64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv8f64
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 8 x s64>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s64>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv1f16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1f16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2f16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2f16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4f16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv4f16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 4 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv8f16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv8f16
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 8 x s16>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s16>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv16f16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv16f16
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 16 x s16>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s16>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv32f16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv32f16
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 32 x s16>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 32 x s16>) = COPY $v8m8
    PseudoRET

...
---
name:            test_args_nxv1b16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv1b16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 1 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 1 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv2b16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv2b16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 2 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 2 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv4b16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8

    ; BOTH-LABEL: name: test_args_nxv4b16
    ; BOTH: liveins: $v8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrnov0b(<vscale x 4 x s16>) = COPY $v8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 4 x s16>) = COPY $v8
    PseudoRET

...
---
name:            test_args_nxv8b16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m2

    ; BOTH-LABEL: name: test_args_nxv8b16
    ; BOTH: liveins: $v8m2
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm2nov0b(<vscale x 8 x s16>) = COPY $v8m2
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 8 x s16>) = COPY $v8m2
    PseudoRET

...
---
name:            test_args_nxv16b16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m4

    ; BOTH-LABEL: name: test_args_nxv16b16
    ; BOTH: liveins: $v8m4
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm4nov0b(<vscale x 16 x s16>) = COPY $v8m4
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 16 x s16>) = COPY $v8m4
    PseudoRET

...
---
name:            test_args_nxv32b16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $v8m8

    ; BOTH-LABEL: name: test_args_nxv32b16
    ; BOTH: liveins: $v8m8
    ; BOTH-NEXT: {{  $}}
    ; BOTH-NEXT: [[COPY:%[0-9]+]]:vrm8nov0b(<vscale x 32 x s16>) = COPY $v8m8
    ; BOTH-NEXT: PseudoRET
    %0:_(<vscale x 32 x s16>) = COPY $v8m8
    PseudoRET

...
